ALTER TABLE users
  ADD COLUMN IF NOT EXISTS email VARCHAR(320) UNIQUE,
  ADD COLUMN IF NOT EXISTS password_hash VARCHAR(512),
  ADD COLUMN IF NOT EXISTS is_verified BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS otp_code VARCHAR(6),
  ADD COLUMN IF NOT EXISTS otp_expires_at TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS ix_users_email ON users (email);
